apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo-servicemesh-networking
spec:
  project: bookinfo
  source:
    repoURL: 'https://github.com/mmartofel/gitops-demo-flow-bookinfo-application'
    path: networking
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: bookinfo
